version: '2.1'

services:

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: always
    network_mode: host
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - $HOME/docker_files/mqtt/data:/mosquitto/data
      - $HOME/docker_files/mqtt/config:/mosquitto/config
      - $HOME/docker_files/mqtt/log:/mosquitto/log
    environment:
      - TZ=America/New_York

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      GF_RENDERING_SERVER_URL: http://192.168.72.2:8081/render
      GF_RENDERING_CALLBACK_URL: http://192.168.72.2:3000/
      GF_LOG_FILTERS: rendering:debug
    network_mode: host
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - $HOME/docker_files/grafana:/var/lib/grafana

  # grafana render
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: "grafana-renderer"
    depends_on:
      grafana:
        condition: service_started

  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    environment:
      - TZ=America/New_York
    network_mode: host
    ports:
      - 8083:8083
      - 8086:8086
    restart: on-failure
    volumes:
      - $HOME/docker_files/influxdb:/var/lib/influxdb

  home-assistant:
    #image: homeassistant/home-assistant:0.110.4    #Specific Version
    image: homeassistant/home-assistant:latest     #Latest Production
    #image: homeassistant/home-assistant:rc          #Latest Beta Code
    container_name: "homeassistant"
    restart: always
    depends_on:
      influxdb:
        condition: service_healthy
      mqtt:
        condition: service_started
    network_mode: host
    ports:
      - 8123:8123
      - 51827:51827
    volumes:
      - $HOME/docker_files/homeassistant/config:/config
    environment:
      - TZ=America/New_York